default: &default
  adapter: postgresql
  encoding: utf8  
  pool: 5
  
development:
  <<: *default
  database: d65bbq1fhkgsmr
  pool: 5
  username: racoboismydgof
  password: 62b4feee1b0c739bfe3d401fc53e7c0f574c3b9ad09c654339d59ec8b96b8f45
  host:     ec2-54-243-235-153.compute-1.amazonaws.com
  sslmode:  require
  
production:
  <<: *default
  database: d65bbq1fhkgsmr
  pool: 5
  username: racoboismydgof
  password: 62b4feee1b0c739bfe3d401fc53e7c0f574c3b9ad09c654339d59ec8b96b8f45
  host:     ec2-54-243-235-153.compute-1.amazonaws.com
  sslmode:  require
  